name: dwi
description: A Flutter project that shows a simple Days Without Incidents app.

version: 2.1.0+7

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Bloc for state management
  flutter_bloc: ^7.0.0-nullsafety.5
  # Value equality
  equatable: ^2.0.0
  # Metadata
  meta: ^1.1.8
  # Local cache
  shared_preferences: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  bloc_test: ^8.0.0-nullsafety.4
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/launcher/dwi-512x512-android.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true
  adaptive_icon_background: "#56F0D4"
  adaptive_icon_foreground: "assets/launcher/dwi-foreground.png"

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/es.json
