name: dwi
description: A Flutter project that shows a simple Days Without Incidents app.
publish_to: none
version: 3.0.0+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  data:
    path: packages/data
  domain:
    path: packages/domain
  equatable: ^2.0.5
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_feather_icons: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  package_info_plus: ^1.4.3+1
  sentry_flutter: ^6.9.1
  upgrader: ^4.8.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6
  wiredash: ^1.5.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  very_good_analysis: ^3.0.1

flutter_icons:
  image_path: 'assets/launcher/dwi-512x512-android.png'
  android: true
  ios: true
  adaptive_icon_background: '#56F0D4'
  adaptive_icon_foreground: 'assets/launcher/dwi-foreground.png'
  remove_alpha_ios: true

flutter_native_splash:
  color: '#56F0D4'
  image: assets/launcher/dwi-foreground.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/launcher/
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
