name: dwi
description: A Flutter project that shows a simple Days Without Incidents app.
publish_to: none
version: 3.1.0+11

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  # Data layer
  data:
    path: packages/data
  # Domain layer
  domain:
    path: packages/domain
  # Value equality
  duration: ^3.0.13
  environment:
    path: packages/environment
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^8.1.4
  # Feather Icons package
  flutter_feather_icons: ^2.0.0
  flutter_localizations:
    sdk: flutter
  # Build Information
  gap: ^3.0.1
  intl: ^0.19.0
  package_info_plus: ^4.2.0
  # Monitoring
  sentry_flutter: ^7.12.0
  # Launcher for URLs
  url_launcher: ^6.2.1
  # UUID
  uuid: ^4.2.1
  # Bug Reporting
  wiredash: ^2.2.0

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  very_good_analysis: ^5.1.0

# dependency_overrides:
#   image: ^4.0.10

flutter_icons:
  image_path: 'assets/launcher/dwi-512x512-android.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true
  adaptive_icon_background: '#56F0D4'
  adaptive_icon_foreground: 'assets/launcher/dwi-foreground.png'
  remove_alpha_ios: true

flutter_native_splash:
  color: '#56F0D4'
  image: assets/launcher/dwi-foreground.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/launcher/
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/WorkSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/WorkSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-ThinItalic.ttf
          weight: 100
          style: italic
