name: domain
description: Domain Package.
version: 1.0.0
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Value equality
  equatable: ^2.0.3
  # UUID
  uuid: ^3.0.4

dev_dependencies:
