name: domain
description: Domain Package.
version: 1.0.0
homepage:
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Value equality
  equatable: ^2.0.5
  # UUID
  uuid: ^4.2.1

dev_dependencies:
  very_good_analysis: ^7.0.0
