update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to the Google Play"
  lane :beta do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: 'beta'
    )
  end
end
